services:
  redis:
    image: redis:latest
    container_name: api-redis
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  redis_test:
    image: redis:latest
    container_name: api_redis_test
    command: [ "redis-server", "--appendonly", "no" ] # no persistence for tests (faster/cleaner)
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  redis:
  redis-config:
